<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Nav_Grievance</name>
   <tag></tag>
   <elementGuidId>16fa6f18-2d08-4687-8742-3ddd3f694128</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b0p0o12i0i0r1']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b0p0o12i0i0r1 > div.fm-button-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7da2a42d-6ef2-4df8-9395-9e31a0505ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fm-button-container</value>
      <webElementGuid>7b972df4-d6ae-435b-9cc5-c1fec07cbced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grievance</value>
      <webElementGuid>51fb9a64-f59c-4dde-a4fe-1c4e73fdb029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b0p0o12i0i0r1&quot;)/div[@class=&quot;fm-button-container&quot;]</value>
      <webElementGuid>b9746752-d410-400c-92ce-3fb33cb6048d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='b0p0o12i0i0r1']/div</value>
      <webElementGuid>01dff982-4b81-4988-a209-2cb13b1a9209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Appraisals'])[1]/following::div[3]</value>
      <webElementGuid>9b0445bc-0237-4ffc-bd32-962b1d39e46f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Training'])[1]/following::div[7]</value>
      <webElementGuid>dcb88643-bd4b-41a1-8c51-efa09a5efc75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/preceding::div[3]</value>
      <webElementGuid>722a8f19-c4b0-4955-b88b-9e4ec76b7881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/button/div</value>
      <webElementGuid>6919c425-2146-40a0-aa06-644ffdc0162d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Grievance' or . = 'Grievance')]</value>
      <webElementGuid>c4517d23-e4dd-40a2-8a49-501ee4ed8bcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
