<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Nav_Employees</name>
   <tag></tag>
   <elementGuidId>8c8b0d07-89da-4985-b4e0-c11ef0c646c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b0p0o8i0i0r1']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b0p0o8i0i0r1 > div.fm-button-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5b1bddaa-2477-4ea0-88b6-6b18d3edc5c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fm-button-container</value>
      <webElementGuid>009c79b1-a2e3-4d84-9684-7f7e18e47e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employees</value>
      <webElementGuid>9560368d-73d1-4e26-915c-c5b45457fd83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b0p0o8i0i0r1&quot;)/div[@class=&quot;fm-button-container&quot;]</value>
      <webElementGuid>d7c2cc48-0fac-4b72-a644-2993e9d42aac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='b0p0o8i0i0r1']/div</value>
      <webElementGuid>19d42683-bfeb-4218-9d2e-08b3d166b9d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::div[3]</value>
      <webElementGuid>43773fa7-c3af-47e6-ac9b-673205de4912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recruitment'])[1]/preceding::div[3]</value>
      <webElementGuid>6f0f9c5b-2b58-47f5-901e-2769613994ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/div</value>
      <webElementGuid>42e25763-b099-4b02-b1b5-48528742706d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Employees' or . = 'Employees')]</value>
      <webElementGuid>56b1a9f0-b9fa-4226-ba0d-3b41f9f7985c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
