<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Nav_Training</name>
   <tag></tag>
   <elementGuidId>d03152f7-b4ec-4ff2-8387-cfd85813a966</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b0p0o13i0i0r1']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b0p0o13i0i0r1 > div.fm-button-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>50d87f9e-cd5c-4beb-8e31-d1e99fedb7dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fm-button-container</value>
      <webElementGuid>f956c2dd-551f-463e-ac12-9ef6ce325640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Training</value>
      <webElementGuid>3e5966db-667c-4c09-abbd-cdc9e28dab17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b0p0o13i0i0r1&quot;)/div[@class=&quot;fm-button-container&quot;]</value>
      <webElementGuid>1bd8587b-05b9-4a44-b4ea-832bdeceb9b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='b0p0o13i0i0r1']/div</value>
      <webElementGuid>394cdc41-67ec-4452-bef6-0c276dc839ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attendance &amp; Payroll'])[1]/following::div[3]</value>
      <webElementGuid>4931e865-a3a3-475e-9d13-6b0e3ba15b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recruitment'])[1]/following::div[7]</value>
      <webElementGuid>04172995-21a1-495e-b018-a3e3a356cf05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Appraisals'])[1]/preceding::div[3]</value>
      <webElementGuid>f0ea8f61-6714-4c21-b059-101bdcff6eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button/div</value>
      <webElementGuid>068c09cf-5331-446d-896d-6e24ec5f2f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Training' or . = 'Training')]</value>
      <webElementGuid>5654d466-ea53-4ec9-8f8a-d5d5baf52c6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
